//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.UI.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScmResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTISCZ.ScmDemand.UI.Resource.ScmResource", typeof(ScmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Other Nomenclatures.
        /// </summary>
        public static string AddNomencaltures {
            get {
                return ResourceManager.GetString("AddNomencaltures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Nomenclature.
        /// </summary>
        public static string AddNomenclature {
            get {
                return ResourceManager.GetString("AddNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AppExit {
            get {
                object obj = ResourceManager.GetObject("AppExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Manager.
        /// </summary>
        public static string ApprovalManager {
            get {
                return ResourceManager.GetString("ApprovalManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Supplier.
        /// </summary>
        public static string ApprovedSupplier {
            get {
                return ResourceManager.GetString("ApprovedSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying of &apos;{0}&apos; failed !!!.
        /// </summary>
        public static string AttachmentCopyFailed {
            get {
                return ResourceManager.GetString("AttachmentCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured. Authorization Failed.
        /// </summary>
        public static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Previous Status.
        /// </summary>
        public static string BackToPreviousStatus {
            get {
                return ResourceManager.GetString("BackToPreviousStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail cannot be sent..
        /// </summary>
        public static string CannotBeSent {
            get {
                return ResourceManager.GetString("CannotBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to Take Over the Demand.
        /// </summary>
        public static string CannotTakeOverDemand {
            get {
                return ResourceManager.GetString("CannotTakeOverDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- All ---.
        /// </summary>
        public static string CmbFilterAll {
            get {
                return ResourceManager.GetString("CmbFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Nomenclature Key.
        /// </summary>
        public static string CopyNomKey {
            get {
                return ResourceManager.GetString("CopyNomKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dashboard {
            get {
                object obj = ResourceManager.GetObject("Dashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was imported.
        /// </summary>
        public static string DataWasImported {
            get {
                return ResourceManager.GetString("DataWasImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during saving process !!!.
        /// </summary>
        public static string DataWasNotSaved {
            get {
                return ResourceManager.GetString("DataWasNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days in Status.
        /// </summary>
        public static string DaysInStatus {
            get {
                return ResourceManager.GetString("DaysInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        public static string Demand {
            get {
                return ResourceManager.GetString("Demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete Demand nr. {0} ?.
        /// </summary>
        public static string DemandDeleteConfirmation {
            get {
                return ResourceManager.GetString("DemandDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Nr..
        /// </summary>
        public static string DemandNr {
            get {
                return ResourceManager.GetString("DemandNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demands.
        /// </summary>
        public static string Demands {
            get {
                return ResourceManager.GetString("Demands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} to {1} from {2}.
        /// </summary>
        public static string DisplayingFromToOf {
            get {
                return ResourceManager.GetString("DisplayingFromToOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string DocCertificates {
            get {
                return ResourceManager.GetString("DocCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string DocCurrency {
            get {
                return ResourceManager.GetString("DocCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP OTIS Breclav package included.
        /// </summary>
        public static string DocDapOtis {
            get {
                return ResourceManager.GetString("DocDapOtis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Condition
        ///Incoterms 2020.
        /// </summary>
        public static string DocDeliveryConditions {
            get {
                return ResourceManager.GetString("DocDeliveryConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Deadline.
        /// </summary>
        public static string DocDemandDeadline {
            get {
                return ResourceManager.GetString("DocDemandDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Requestor.
        /// </summary>
        public static string DocDemandRequestor {
            get {
                return ResourceManager.GetString("DocDemandRequestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DocDepartment {
            get {
                return ResourceManager.GetString("DocDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for EUR1.
        /// </summary>
        public static string DocEUR1Request {
            get {
                return ResourceManager.GetString("DocEUR1Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LT.
        /// </summary>
        public static string DocLT {
            get {
                return ResourceManager.GetString("DocLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJ.
        /// </summary>
        public static string DocMj {
            get {
                return ResourceManager.GetString("DocMj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOQ.
        /// </summary>
        public static string DocMOQ {
            get {
                return ResourceManager.GetString("DocMOQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature.
        /// </summary>
        public static string DocNomenclature {
            get {
                return ResourceManager.GetString("DocNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer was created by.
        /// </summary>
        public static string DocOfferCreatedBy {
            get {
                return ResourceManager.GetString("DocOfferCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Deadline.
        /// </summary>
        public static string DocOfferDeadline {
            get {
                return ResourceManager.GetString("DocOfferDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer&apos;s Expire Date.
        /// </summary>
        public static string DocOfferExpireDate {
            get {
                return ResourceManager.GetString("DocOfferExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Follows EUR1.
        /// </summary>
        public static string DocOfferFollows {
            get {
                return ResourceManager.GetString("DocOfferFollows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Conditions.
        /// </summary>
        public static string DocOtherConditions {
            get {
                return ResourceManager.GetString("DocOtherConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTIS Drawing Nr..
        /// </summary>
        public static string DocOtisDrawNr {
            get {
                return ResourceManager.GetString("DocOtisDrawNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallets - goods may only be packed on EUR pallets. Other types of pallets are prohibited. Pallets must be calculated in the price of the goods..
        /// </summary>
        public static string DocPaletsConditions {
            get {
                return ResourceManager.GetString("DocPaletsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part name.
        /// </summary>
        public static string DocPartNane {
            get {
                return ResourceManager.GetString("DocPartNane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcs.
        /// </summary>
        public static string DocPcs {
            get {
                return ResourceManager.GetString("DocPcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone nr..
        /// </summary>
        public static string DocPhoneNr {
            get {
                return ResourceManager.GetString("DocPhoneNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price
        ///(FCA/DAP).
        /// </summary>
        public static string DocPriceUnit {
            get {
                return ResourceManager.GetString("DocPriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string DocProjectName {
            get {
                return ResourceManager.GetString("DocProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project nr:.
        /// </summary>
        public static string DocProjectNr {
            get {
                return ResourceManager.GetString("DocProjectNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Certificates.
        /// </summary>
        public static string DocRequestedCertificates {
            get {
                return ResourceManager.GetString("DocRequestedCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFQ Document.
        /// </summary>
        public static string DocRfqDocument {
            get {
                return ResourceManager.GetString("DocRfqDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string DocSupplierName {
            get {
                return ResourceManager.GetString("DocSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Offer Nr.
        /// </summary>
        public static string DocSupplierOfferNr {
            get {
                return ResourceManager.GetString("DocSupplierOfferNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers Part Nr..
        /// </summary>
        public static string DocSupplierPartNr {
            get {
                return ResourceManager.GetString("DocSupplierPartNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eMail Address.
        /// </summary>
        public static string eMail {
            get {
                return ResourceManager.GetString("eMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Form Fields.
        /// </summary>
        public static string EnterMandatoryTitle {
            get {
                return ResourceManager.GetString("EnterMandatoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mandatory Values.
        /// </summary>
        public static string EnterMandatoryValues {
            get {
                return ResourceManager.GetString("EnterMandatoryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Nomenclature Number.
        /// </summary>
        public static string EnterNomenclatureKey {
            get {
                return ResourceManager.GetString("EnterNomenclatureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Nomenclature Name.
        /// </summary>
        public static string EnterNomenclatureName {
            get {
                return ResourceManager.GetString("EnterNomenclatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Price.
        /// </summary>
        public static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid data. Check error message in in Form..
        /// </summary>
        public static string EnterValidData {
            get {
                return ResourceManager.GetString("EnterValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Mail Addresses.
        /// </summary>
        public static string EnterValidMailAddresses {
            get {
                return ResourceManager.GetString("EnterValidMailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scm Demand Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Demand.
        /// </summary>
        public static string FinishDemand {
            get {
                return ResourceManager.GetString("FinishDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix errors..
        /// </summary>
        public static string FixErrors {
            get {
                return ResourceManager.GetString("FixErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist..
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FromToFrom {
            get {
                return ResourceManager.GetString("FromToFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string FromToTo {
            get {
                return ResourceManager.GetString("FromToTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Page.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Prodis File.
        /// </summary>
        public static string ImportProdisFile {
            get {
                return ResourceManager.GetString("ImportProdisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Remark.
        /// </summary>
        public static string InsertRemark {
            get {
                return ResourceManager.GetString("InsertRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Import Date.
        /// </summary>
        public static string LastImportDate {
            get {
                return ResourceManager.GetString("LastImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastPage.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status modif. date.
        /// </summary>
        public static string LastStatusModifDate {
            get {
                return ResourceManager.GetString("LastStatusModifDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data ....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me the Demand in Bcc.
        /// </summary>
        public static string MailBcc {
            get {
                return ResourceManager.GetString("MailBcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Supplier,
        ///we send Demand nr. {0} in attachment.
        ///
        ///Best regards.
        /// </summary>
        public static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MailCc {
            get {
                return ResourceManager.GetString("MailCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Address is not in correct format.
        /// </summary>
        public static string MailFormatError {
            get {
                return ResourceManager.GetString("MailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Language.
        /// </summary>
        public static string MailLanguage {
            get {
                return ResourceManager.GetString("MailLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string MailRecipient {
            get {
                return ResourceManager.GetString("MailRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mails.
        /// </summary>
        public static string Mails {
            get {
                return ResourceManager.GetString("Mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string MailSender {
            get {
                return ResourceManager.GetString("MailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailWasSent.
        /// </summary>
        public static string MailWasSent {
            get {
                return ResourceManager.GetString("MailWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Group.
        /// </summary>
        public static string MaterialGroup {
            get {
                return ResourceManager.GetString("MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone Nr..
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameIt {
            get {
                return ResourceManager.GetString("NameIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Demand.
        /// </summary>
        public static string NewDemand {
            get {
                return ResourceManager.GetString("NewDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Supplier.
        /// </summary>
        public static string NewSupplier {
            get {
                return ResourceManager.GetString("NewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Limit.
        /// </summary>
        public static string NoLimit {
            get {
                return ResourceManager.GetString("NoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature.
        /// </summary>
        public static string Nomenclature {
            get {
                return ResourceManager.GetString("Nomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatures.
        /// </summary>
        public static string Nomenclatures {
            get {
                return ResourceManager.GetString("Nomenclatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Nomenclatures were not loaded.
        /// </summary>
        public static string NomenclaturesLoadedFailed {
            get {
                return ResourceManager.GetString("NomenclaturesLoadedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatures were loaded successfully.
        /// </summary>
        public static string NomenclaturesLoadedSuccessfully {
            get {
                return ResourceManager.GetString("NomenclaturesLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string NomenclatureSource {
            get {
                return ResourceManager.GetString("NomenclatureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature {0} will be evaluated as part of Demand nr. {1}. 
        ///You can remove the nomenclature from this Demand.
        /// </summary>
        public static string NomenclatureWillBeEvaluatedAsPartOf {
            get {
                return ResourceManager.GetString("NomenclatureWillBeEvaluatedAsPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized for this operation.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Demands Waiting for my action.
        /// </summary>
        public static string OnlyMyDemands {
            get {
                return ResourceManager.GetString("OnlyMyDemands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Demands.
        /// </summary>
        public static string OtherDemands {
            get {
                return ResourceManager.GetString("OtherDemands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otis Attachment.
        /// </summary>
        public static string OtisAttachment {
            get {
                return ResourceManager.GetString("OtisAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Demands.
        /// </summary>
        public static string PendingDemands {
            get {
                return ResourceManager.GetString("PendingDemands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Demands and Nomenclatures.
        /// </summary>
        public static string PendingDemandsNomenclatures {
            get {
                return ResourceManager.GetString("PendingDemandsNomenclatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Items.
        /// </summary>
        public static string PendingItems {
            get {
                return ResourceManager.GetString("PendingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Nomenclatures.
        /// </summary>
        public static string PendingNomenclatures {
            get {
                return ResourceManager.GetString("PendingNomenclatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Nr..
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price was set in Prodis. Price = {0}.
        /// </summary>
        public static string PriceWasSetConfirmed {
            get {
                return ResourceManager.GetString("PriceWasSetConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodis Price Set.
        /// </summary>
        public static string ProdisPriceSet {
            get {
                return ResourceManager.GetString("ProdisPriceSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM Referent.
        /// </summary>
        public static string Referent {
            get {
                return ResourceManager.GetString("Referent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor.
        /// </summary>
        public static string Requestor {
            get {
                return ResourceManager.GetString("Requestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ScmDemand {
            get {
                object obj = ResourceManager.GetObject("ScmDemand", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Approval Manager.
        /// </summary>
        public static string SelectAppMan {
            get {
                return ResourceManager.GetString("SelectAppMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Currency.
        /// </summary>
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Nomenclatures.
        /// </summary>
        public static string SelectedNomenclature {
            get {
                return ResourceManager.GetString("SelectedNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Suppliers.
        /// </summary>
        public static string SelectedSuppliers {
            get {
                return ResourceManager.GetString("SelectedSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLang {
            get {
                return ResourceManager.GetString("SelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Nomenclatures.
        /// </summary>
        public static string SelectNomenclatures {
            get {
                return ResourceManager.GetString("SelectNomenclatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supplier(s).
        /// </summary>
        public static string SelectSupplier {
            get {
                return ResourceManager.GetString("SelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send for Approval.
        /// </summary>
        public static string SendForApproval {
            get {
                return ResourceManager.GetString("SendForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to me.
        /// </summary>
        public static string SendToMe {
            get {
                return ResourceManager.GetString("SendToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Supplier.
        /// </summary>
        public static string SendToSupplier {
            get {
                return ResourceManager.GetString("SendToSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string StatusApproved {
            get {
                return ResourceManager.GetString("StatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed by Referent.
        /// </summary>
        public static string StatusClosed {
            get {
                return ResourceManager.GetString("StatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string StatusDraft {
            get {
                return ResourceManager.GetString("StatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price was set in Prodis.
        /// </summary>
        public static string StatusPriceWasSet {
            get {
                return ResourceManager.GetString("StatusPriceWasSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price was confirmed in Prodis.
        /// </summary>
        public static string StatusPriceWasSetConfirmed {
            get {
                return ResourceManager.GetString("StatusPriceWasSetConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string StatusRejected {
            get {
                return ResourceManager.GetString("StatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to Supplier.
        /// </summary>
        public static string StatusSentToSupplier {
            get {
                return ResourceManager.GetString("StatusSentToSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Replied.
        /// </summary>
        public static string StatusSupplierReplied {
            get {
                return ResourceManager.GetString("StatusSupplierReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StatusUnknown {
            get {
                return ResourceManager.GetString("StatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Approval.
        /// </summary>
        public static string StatusWaitForApproval {
            get {
                return ResourceManager.GetString("StatusWaitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List.
        /// </summary>
        public static string StatusWoDemand {
            get {
                return ResourceManager.GetString("StatusWoDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Price.
        /// </summary>
        public static string SuggestedPrice {
            get {
                return ResourceManager.GetString("SuggestedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier&apos;s Attachments.
        /// </summary>
        public static string SupplierAttachment {
            get {
                return ResourceManager.GetString("SupplierAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Id.
        /// </summary>
        public static string SupplierId {
            get {
                return ResourceManager.GetString("SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Over.
        /// </summary>
        public static string TakeOver {
            get {
                return ResourceManager.GetString("TakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        public static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Nomenclature.
        /// </summary>
        public static string UserNomenclature {
            get {
                return ResourceManager.GetString("UserNomenclature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ({0}) are not Authorized to Use the &apos;SCM Demand&apos; application.
        /// </summary>
        public static string YouAreNotAuthorized {
            get {
                return ResourceManager.GetString("YouAreNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
