//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Demand
    {
        public int id { get; set; }
        public int version { get; set; }
        public int status_id { get; set; }
        public string remark { get; set; }
        public Nullable<bool> is_requestor_acive { get; set; }
        public Nullable<bool> is_app_man_active { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual Demand_Status Demand_Status { get; set; }
    }
}
