//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachment()
        {
            this.Demand_Attachment = new HashSet<Demand_Attachment>();
        }
    
        public int id { get; set; }
        public string file_name { get; set; }
        public byte[] file_content { get; set; }
        public byte[] file_icon { get; set; }
        public System.DateTime modif_date { get; set; }
        public int modif_user_id { get; set; }
    
        public virtual ScmUser ScmUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demand_Attachment> Demand_Attachment { get; set; }
    }
}
