//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand_Nomenclature
    {
        public int demand_id { get; set; }
        public int demand_version { get; set; }
        public int nomenclature_id { get; set; }
        public int nomenclature_version { get; set; }
        public int status_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> locked_by_demand_id { get; set; }
        public Nullable<int> locked_by_demand_version { get; set; }
        public int modif_user_id { get; set; }
        public System.DateTime modif_date { get; set; }
        public int id { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Demand Demand { get; set; }
        public virtual Demand DemandLock { get; set; }
        public virtual Nomenclature Nomenclature { get; set; }
        public virtual Nomenclature_Status Nomenclature_Status { get; set; }
        public virtual ScmUser ScmUser { get; set; }
    }
}
