//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.Demand_Attachment = new HashSet<Demand_Attachment>();
            this.Demand_Nomenclature = new HashSet<Demand_Nomenclature>();
            this.DemandNomenclatureLock = new HashSet<Demand_Nomenclature>();
            this.Remark = new HashSet<Remark>();
        }
    
        public int id { get; set; }
        public int version { get; set; }
        public string demand_nr { get; set; }
        public int supplier_id { get; set; }
        public int requestor_id { get; set; }
        public Nullable<int> app_man_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime last_status_modif_date { get; set; }
        public bool last_version { get; set; }
        public bool is_active { get; set; }
        public System.DateTime modif_date { get; set; }
        public int modif_user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demand_Attachment> Demand_Attachment { get; set; }
        public virtual Demand_Status Demand_Status { get; set; }
        public virtual ScmUser Requestor { get; set; }
        public virtual ScmUser ScmUser1 { get; set; }
        public virtual ScmUser AppMan { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Active_Demand Active_Demand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demand_Nomenclature> Demand_Nomenclature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demand_Nomenclature> DemandNomenclatureLock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remark> Remark { get; set; }
    }
}
