//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand_Attachment
    {
        public int demand_id { get; set; }
        public int demand_version { get; set; }
        public int attachment_id { get; set; }
        public int att_type { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Demand Demand { get; set; }
    }
}
