//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomenclature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nomenclature()
        {
            this.Demand_Nomenclature = new HashSet<Demand_Nomenclature>();
        }
    
        public int id { get; set; }
        public int version { get; set; }
        public string nomenclature_key { get; set; }
        public string name { get; set; }
        public string name_wo_dia { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> material_group_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> create_user_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> evaluation_method_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime last_status_modif_date { get; set; }
        public System.DateTime import_date { get; set; }
        public bool last_version { get; set; }
        public bool is_active { get; set; }
        public System.DateTime modif_date { get; set; }
        public int modif_user_id { get; set; }
        public string specification { get; set; }
        public string specification_wo_dia { get; set; }
        public int source_id { get; set; }
        public bool is_plnaknavrh { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual EvaluationMethod EvaluationMethod { get; set; }
        public virtual Material_Group Material_Group { get; set; }
        public virtual ScmUser ScmUser { get; set; }
        public virtual ScmUser ScmUser1 { get; set; }
        public virtual ScmUser ScmUser2 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Nomenclature_Status Nomenclature_Status { get; set; }
        public virtual Active_Nomenclature Active_Nomenclature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demand_Nomenclature> Demand_Nomenclature { get; set; }
        public virtual Nomenclature_Source Nomenclature_Source { get; set; }
    }
}
