//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark
    {
        public int id { get; set; }
        public int demand_id { get; set; }
        public int demand_version { get; set; }
        public string remark_text { get; set; }
        public Nullable<System.DateTime> read_date { get; set; }
        public int modif_user_id { get; set; }
        public System.DateTime modif_date { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual ScmUser ScmUser { get; set; }
    }
}
