//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScmDemandEntities : DbContext
    {
        public ScmDemandEntities()
            : base("name=ScmDemandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Demand> Demand { get; set; }
        public virtual DbSet<Demand_Attachment> Demand_Attachment { get; set; }
        public virtual DbSet<Demand_LastNr> Demand_LastNr { get; set; }
        public virtual DbSet<Demand_Status> Demand_Status { get; set; }
        public virtual DbSet<EvaluationMethod> EvaluationMethod { get; set; }
        public virtual DbSet<Material_Group> Material_Group { get; set; }
        public virtual DbSet<Nomenclature> Nomenclature { get; set; }
        public virtual DbSet<Nomenclature_Status> Nomenclature_Status { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ScmSetting> ScmSetting { get; set; }
        public virtual DbSet<ScmUser> ScmUser { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<User_Setting> User_Setting { get; set; }
        public virtual DbSet<Active_Demand> Active_Demand { get; set; }
        public virtual DbSet<Active_Nomenclature> Active_Nomenclature { get; set; }
        public virtual DbSet<Last_Import> Last_Import { get; set; }
        public virtual DbSet<Supplier_Contact> Supplier_Contact { get; set; }
        public virtual DbSet<Source_File> Source_File { get; set; }
        public virtual DbSet<Demand_Nomenclature> Demand_Nomenclature { get; set; }
        public virtual DbSet<Remark> Remark { get; set; }
        public virtual DbSet<Nomenclature_Source> Nomenclature_Source { get; set; }
    }
}
