//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTISCZ.ScmDemand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Demand = new HashSet<Demand>();
            this.Supplier_Contact = new HashSet<Supplier_Contact>();
        }
    
        public int id { get; set; }
        public string supp_name { get; set; }
        public string supp_name_wo_dia { get; set; }
        public string supplier_id { get; set; }
        public string dic { get; set; }
        public string country { get; set; }
        public Nullable<bool> vat { get; set; }
        public string contact_person { get; set; }
        public string phone { get; set; }
        public string mobile_phone { get; set; }
        public string fax { get; set; }
        public string street_part1 { get; set; }
        public string street_part2 { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public Nullable<int> creditor_group { get; set; }
        public string bank_account { get; set; }
        public string lang { get; set; }
        public string email_used { get; set; }
        public bool is_approved { get; set; }
        public bool active { get; set; }
        public System.DateTime modif_date { get; set; }
        public int modif_user_id { get; set; }
        public string street_part1_wo_dia { get; set; }
        public string street_part2_wo_dia { get; set; }
        public string city_wo_dia { get; set; }
        public string country_wo_dia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demand> Demand { get; set; }
        public virtual ScmUser ScmUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Contact> Supplier_Contact { get; set; }
    }
}
