//*************************************************************************************
//* This classes were generated by ScmDemandDdGenerator.sql script                          *
//*************************************************************************************
using System;

namespace OTISCZ.ScmDemand.Model.DataDictionary {
    #region NomenclatureSource
    public class NomenclatureSourceData {

        #region Constants
        public const string TABLE_NAME = "NOMENCLATURE_SOURCE";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region DemandStatus
    public class DemandStatusData {

        #region Constants
        public const string TABLE_NAME = "DEMAND_STATUS";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region DemandLastnr
    public class DemandLastnrData {

        #region Constants
        public const string TABLE_NAME = "DEMAND_LASTNR";
        public const string ID_FIELD = "id";
        public const string LAST_NR_FIELD = "last_nr";
        public const string YEAR_FIELD = "year";

        #endregion
    }
    #endregion

    #region Attachment
    public class AttachmentData {

        #region Constants
        public const string TABLE_NAME = "ATTACHMENT";
        public const string ID_FIELD = "id";
        public const string FILE_NAME_FIELD = "file_name";
        public const string FILE_CONTENT_FIELD = "file_content";
        public const string FILE_ICON_FIELD = "file_icon";
        public const string MODIF_DATE_FIELD = "modif_date";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";

        public const int FILE_NAME_LENGTH = 1500;
        #endregion
    }
    #endregion

    #region NomenclatureStatus
    public class NomenclatureStatusData {

        #region Constants
        public const string TABLE_NAME = "NOMENCLATURE_STATUS";
        public const string ID_FIELD = "id";
        public const string STATUS_NAME_FIELD = "status_name";

        public const int STATUS_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region ActiveDemand
    public class ActiveDemandData {

        #region Constants
        public const string TABLE_NAME = "ACTIVE_DEMAND";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string STATUS_ID_FIELD = "status_id";
        public const string IS_REQUESTOR_ACIVE_FIELD = "is_requestor_acive";
        public const string IS_APP_MAN_ACTIVE_FIELD = "is_app_man_active";
        public const string REMARK_FIELD = "remark";

        public const int REMARK_LENGTH = 500;
        #endregion
    }
    #endregion

    #region Role
    public class RoleData {

        #region Constants
        public const string TABLE_NAME = "ROLE";
        public const string ID_FIELD = "id";
        public const string ROLE_NAME_FIELD = "role_name";

        public const int ROLE_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region SourceFile
    public class SourceFileData {

        #region Constants
        public const string TABLE_NAME = "SOURCE_FILE";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";
        public const string LAST_MODIFICATION_DATE_FIELD = "last_modification_date";
        public const string STATUS_FIELD = "status";
        public const string IMPORT_DATE_FIELD = "import_date";
        public const string IMPORT_USER_ID_FIELD = "import_user_id";

        public const int NAME_LENGTH = 0;
        #endregion
    }
    #endregion

    #region UserRole
    public class UserRoleData {

        #region Constants
        public const string TABLE_NAME = "USER_ROLE";
        public const string USER_ID_FIELD = "user_id";
        public const string ROLE_ID_FIELD = "role_id";

        #endregion
    }
    #endregion

    #region Sysdiagrams
    public class SysdiagramsData {

        #region Constants
        public const string TABLE_NAME = "SYSDIAGRAMS";
        public const string NAME_FIELD = "name";
        public const string PRINCIPAL_ID_FIELD = "principal_id";
        public const string DIAGRAM_ID_FIELD = "diagram_id";
        public const string VERSION_FIELD = "version";
        public const string DEFINITION_FIELD = "definition";

        public const int NAME_LENGTH = 128;
        #endregion
    }
    #endregion

    #region Company
    public class CompanyData {

        #region Constants
        public const string TABLE_NAME = "COMPANY";
        public const string ID_FIELD = "id";
        public const string COMPANY_FIELD = "company";

        public const int COMPANY_LENGTH = 50;
        #endregion
    }
    #endregion

    #region ActiveNomenclature
    public class ActiveNomenclatureData {

        #region Constants
        public const string TABLE_NAME = "ACTIVE_NOMENCLATURE";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string REMARK_FIELD = "remark";

        public const int REMARK_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Scmsetting
    public class ScmsettingData {

        #region Constants
        public const string TABLE_NAME = "SCMSETTING";
        public const string ID_FIELD = "id";
        public const string PRODIS_INPUT_FOLDER_FIELD = "prodis_input_folder";
        public const string PRODIS_PRICE_INPUT_FOLDER_FIELD = "prodis_price_input_folder";
        public const string LAST_IMPORT_DATE_FIELD = "last_import_date";

        public const int PRODIS_INPUT_FOLDER_LENGTH = 500;
        public const int PRODIS_PRICE_INPUT_FOLDER_LENGTH = 500;
        #endregion
    }
    #endregion

    #region Unit
    public class UnitData {

        #region Constants
        public const string TABLE_NAME = "UNIT";
        public const string ID_FIELD = "id";
        public const string CODE_FIELD = "code";
        public const string DESCRIPTION_FIELD = "description";

        public const int CODE_LENGTH = 50;
        public const int DESCRIPTION_LENGTH = 150;
        #endregion
    }
    #endregion

    #region SupplierContact
    public class SupplierContactData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIER_CONTACT";
        public const string ID_FIELD = "id";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string FIRST_NAME_FIELD = "first_name";
        public const string SURNAME_FIELD = "surname";
        public const string EMAIL_FIELD = "email";
        public const string PHONE_NR_FIELD = "phone_nr";
        public const string PHONE_NR2_FIELD = "phone_nr2";
        public const string MODIF_DATE_FIELD = "modif_date";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";

        public const int FIRST_NAME_LENGTH = 50;
        public const int SURNAME_LENGTH = 50;
        public const int EMAIL_LENGTH = 50;
        public const int PHONE_NR_LENGTH = 50;
        public const int PHONE_NR2_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Nomenclature
    public class NomenclatureData {

        #region Constants
        public const string TABLE_NAME = "NOMENCLATURE";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string NOMENCLATURE_KEY_FIELD = "nomenclature_key";
        public const string NAME_FIELD = "name";
        public const string NAME_WO_DIA_FIELD = "name_wo_dia";
        public const string SPECIFICATION_FIELD = "specification";
        public const string SPECIFICATION_WO_DIA_FIELD = "specification_wo_dia";
        public const string UNIT_ID_FIELD = "unit_id";
        public const string MATERIAL_GROUP_ID_FIELD = "material_group_id";
        public const string COMPANY_ID_FIELD = "company_id";
        public const string BUYER_ID_FIELD = "buyer_id";
        public const string CREATED_DATE_FIELD = "created_date";
        public const string CREATE_USER_ID_FIELD = "create_user_id";
        public const string PRICE_FIELD = "price";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string EVALUATION_METHOD_ID_FIELD = "evaluation_method_id";
        public const string STATUS_ID_FIELD = "status_id";
        public const string LAST_STATUS_MODIF_DATE_FIELD = "last_status_modif_date";
        public const string IMPORT_DATE_FIELD = "import_date";
        public const string SOURCE_ID_FIELD = "source_id";
        public const string IS_PLNAKNAVRH_FIELD = "is_plnaknavrh";
        public const string LAST_VERSION_FIELD = "last_version";
        public const string IS_ACTIVE_FIELD = "is_active";
        public const string MODIF_DATE_FIELD = "modif_date";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";

        public const int NOMENCLATURE_KEY_LENGTH = 50;
        public const int NAME_LENGTH = 150;
        public const int NAME_WO_DIA_LENGTH = 150;
        public const int SPECIFICATION_LENGTH = 500;
        public const int SPECIFICATION_WO_DIA_LENGTH = 500;
        #endregion
    }
    #endregion

    #region MaterialGroup
    public class MaterialGroupData {

        #region Constants
        public const string TABLE_NAME = "MATERIAL_GROUP";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region LastImport
    public class LastImportData {

        #region Constants
        public const string TABLE_NAME = "LAST_IMPORT";
        public const string ID_FIELD = "id";
        public const string LAST_NOMENCLATURE_IMPORT_DATE_FIELD = "last_nomenclature_import_date";

        #endregion
    }
    #endregion

    #region Demand
    public class DemandData {

        #region Constants
        public const string TABLE_NAME = "DEMAND";
        public const string ID_FIELD = "id";
        public const string VERSION_FIELD = "version";
        public const string DEMAND_NR_FIELD = "demand_nr";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string REQUESTOR_ID_FIELD = "requestor_id";
        public const string APP_MAN_ID_FIELD = "app_man_id";
        public const string STATUS_ID_FIELD = "status_id";
        public const string CREATED_DATE_FIELD = "created_date";
        public const string LAST_STATUS_MODIF_DATE_FIELD = "last_status_modif_date";
        public const string LAST_VERSION_FIELD = "last_version";
        public const string IS_ACTIVE_FIELD = "is_active";
        public const string MODIF_DATE_FIELD = "modif_date";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";

        public const int DEMAND_NR_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Evaluationmethod
    public class EvaluationmethodData {

        #region Constants
        public const string TABLE_NAME = "EVALUATIONMETHOD";
        public const string ID_FIELD = "id";
        public const string NAME_FIELD = "name";

        public const int NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Currency
    public class CurrencyData {

        #region Constants
        public const string TABLE_NAME = "CURRENCY";
        public const string ID_FIELD = "id";
        public const string CURRENCY_CODE_FIELD = "currency_code";
        public const string CURRENCY_NAME_FIELD = "currency_name";
        public const string IS_ACTIVE_FIELD = "is_active";

        public const int CURRENCY_CODE_LENGTH = 10;
        public const int CURRENCY_NAME_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Supplier
    public class SupplierData {

        #region Constants
        public const string TABLE_NAME = "SUPPLIER";
        public const string ID_FIELD = "id";
        public const string SUPP_NAME_FIELD = "supp_name";
        public const string SUPP_NAME_WO_DIA_FIELD = "supp_name_wo_dia";
        public const string SUPPLIER_ID_FIELD = "supplier_id";
        public const string DIC_FIELD = "dic";
        public const string COUNTRY_FIELD = "country";
        public const string COUNTRY_WO_DIA_FIELD = "country_wo_dia";
        public const string VAT_FIELD = "vat";
        public const string CONTACT_PERSON_FIELD = "contact_person";
        public const string PHONE_FIELD = "phone";
        public const string MOBILE_PHONE_FIELD = "mobile_phone";
        public const string FAX_FIELD = "fax";
        public const string STREET_PART1_FIELD = "street_part1";
        public const string STREET_PART1_WO_DIA_FIELD = "street_part1_wo_dia";
        public const string STREET_PART2_FIELD = "street_part2";
        public const string STREET_PART2_WO_DIA_FIELD = "street_part2_wo_dia";
        public const string CITY_FIELD = "city";
        public const string CITY_WO_DIA_FIELD = "city_wo_dia";
        public const string ZIP_FIELD = "zip";
        public const string EMAIL_FIELD = "email";
        public const string CREDITOR_GROUP_FIELD = "creditor_group";
        public const string BANK_ACCOUNT_FIELD = "bank_account";
        public const string LANG_FIELD = "lang";
        public const string EMAIL_USED_FIELD = "email_used";
        public const string IS_APPROVED_FIELD = "is_approved";
        public const string ACTIVE_FIELD = "active";
        public const string MODIF_DATE_FIELD = "modif_date";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";

        public const int SUPP_NAME_LENGTH = 400;
        public const int SUPP_NAME_WO_DIA_LENGTH = 400;
        public const int SUPPLIER_ID_LENGTH = 50;
        public const int DIC_LENGTH = 50;
        public const int COUNTRY_LENGTH = 100;
        public const int COUNTRY_WO_DIA_LENGTH = 100;
        public const int CONTACT_PERSON_LENGTH = 400;
        public const int PHONE_LENGTH = 50;
        public const int MOBILE_PHONE_LENGTH = 50;
        public const int FAX_LENGTH = 50;
        public const int STREET_PART1_LENGTH = 500;
        public const int STREET_PART1_WO_DIA_LENGTH = 500;
        public const int STREET_PART2_LENGTH = 150;
        public const int STREET_PART2_WO_DIA_LENGTH = 150;
        public const int CITY_LENGTH = 150;
        public const int CITY_WO_DIA_LENGTH = 150;
        public const int ZIP_LENGTH = 25;
        public const int EMAIL_LENGTH = 150;
        public const int BANK_ACCOUNT_LENGTH = 50;
        public const int LANG_LENGTH = 20;
        public const int EMAIL_USED_LENGTH = 150;
        #endregion
    }
    #endregion

    #region DemandNomenclature
    public class DemandNomenclatureData {

        #region Constants
        public const string TABLE_NAME = "DEMAND_NOMENCLATURE";
        public const string ID_FIELD = "id";
        public const string DEMAND_ID_FIELD = "demand_id";
        public const string DEMAND_VERSION_FIELD = "demand_version";
        public const string NOMENCLATURE_ID_FIELD = "nomenclature_id";
        public const string NOMENCLATURE_VERSION_FIELD = "nomenclature_version";
        public const string STATUS_ID_FIELD = "status_id";
        public const string PRICE_FIELD = "price";
        public const string CURRENCY_ID_FIELD = "currency_id";
        public const string LOCKED_BY_DEMAND_ID_FIELD = "locked_by_demand_id";
        public const string LOCKED_BY_DEMAND_VERSION_FIELD = "locked_by_demand_version";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";
        public const string MODIF_DATE_FIELD = "modif_date";

        #endregion
    }
    #endregion

    #region Scmuser
    public class ScmuserData {

        #region Constants
        public const string TABLE_NAME = "SCMUSER";
        public const string ID_FIELD = "id";
        public const string USER_NAME_FIELD = "user_name";
        public const string FIRST_NAME_FIELD = "first_name";
        public const string SURNAME_FIELD = "surname";
        public const string FIRST_NAME_WO_DIA_FIELD = "first_name_wo_dia";
        public const string SURNAME_WO_FIELD = "surname_wo";
        public const string EMAIL_FIELD = "email";
        public const string PHONE_NR_FIELD = "phone_nr";
        public const string IS_ACTIVE_FIELD = "is_active";

        public const int USER_NAME_LENGTH = 50;
        public const int FIRST_NAME_LENGTH = 150;
        public const int SURNAME_LENGTH = 150;
        public const int FIRST_NAME_WO_DIA_LENGTH = 150;
        public const int SURNAME_WO_LENGTH = 150;
        public const int EMAIL_LENGTH = 150;
        public const int PHONE_NR_LENGTH = 50;
        #endregion
    }
    #endregion

    #region Remark
    public class RemarkData {

        #region Constants
        public const string TABLE_NAME = "REMARK";
        public const string ID_FIELD = "id";
        public const string DEMAND_ID_FIELD = "demand_id";
        public const string DEMAND_VERSION_FIELD = "demand_version";
        public const string REMARK_TEXT_FIELD = "remark_text";
        public const string READ_DATE_FIELD = "read_date";
        public const string MODIF_USER_ID_FIELD = "modif_user_id";
        public const string MODIF_DATE_FIELD = "modif_date";

        #endregion
    }
    #endregion

    #region UserSetting
    public class UserSettingData {

        #region Constants
        public const string TABLE_NAME = "USER_SETTING";
        public const string USER_ID_FIELD = "user_id";
        public const string CULTURE_FIELD = "culture";

        public const int CULTURE_LENGTH = 50;
        #endregion
    }
    #endregion

    #region DemandAttachment
    public class DemandAttachmentData {

        #region Constants
        public const string TABLE_NAME = "DEMAND_ATTACHMENT";
        public const string DEMAND_ID_FIELD = "demand_id";
        public const string DEMAND_VERSION_FIELD = "demand_version";
        public const string ATTACHMENT_ID_FIELD = "attachment_id";
        public const string ATT_TYPE_FIELD = "att_type";

        #endregion
    }
    #endregion

}
